source 'https://rubygems.org'

gem 'travis'
gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-contrib'
gem 'shotgun'
gem 'zurb-foundation'
gem 'compass'
gem 'rake'
gem 'pony'
gem 'newrelic_rpm'
gem 'faker'
gem 'uuid'
